syntax = "proto3";

option csharp_namespace = "gov_messenger";

package messenger;

service Messenger {
  rpc Login (LoginRequest) returns (LoginResponse);

  rpc GetUser (GetUserRequest) returns (GetUserResponse);

  rpc GetChats (GetChatsRequest) returns (GetChatsResponse);
  rpc CreateChat (CreateChatRequest) returns (CreateChatResponse);

  rpc GetMessages (GetMessagesRequest) returns (GetMessagesResponse);
  rpc SendMessage (SendMessageRequest) returns (SendMessageResponse);

  rpc StreamMessages (StreamMessagesRequest) returns (stream Message);

  rpc RequestEmailCode (RequestEmailCodeRequest) returns (RequestEmailCodeResponse);
  rpc VerifyEmailCode (VerifyEmailCodeRequest) returns (LoginResponse);

  rpc GetUsers (GetUsersRequest) returns (GetUsersResponse);
}

service Admin {  
  rpc CreateUser (CreateUserRequest) returns (UserResponse);
  rpc GetUserByEmail (GetUserByEmailRequest) returns (GetUserByEmailResponse);
  rpc GetAllUsers (GetAllUsersRequest) returns (GetAllUsersResponse);
  rpc EditUser (EditUserRequest) returns (UserResponse);
  rpc DeleteUser (DeleteUserRequest) returns (UserResponse);
}

// Authentication

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  bool success = 1;
  string token = 2;
  User user = 3;
  string error = 4;
}

// Users

message User {
  string id = 1;
  string email = 2;
  string name = 3;
  string avatar_url = 4;
  string status = 5;
  int64 last_seen = 6;
  string role = 7;
  bool is_blocked = 8;
  bool is_deleted = 9;
}

message GetUserRequest {}

message GetUserResponse {
  User user = 1;
  string error = 2;
}

// Getting users
message GetUsersRequest {
    string search = 1;
}

message GetUsersResponse {
    repeated User users = 1;
    string error = 2;
}

// Chats

enum ChatType {
  PRIVATE = 0;
  GROUP = 1;
}

message Chat {
  string id = 1;
  string name = 2;
  ChatType type = 3;
  string avatar_url = 4;
  repeated User participants = 5;
  Message last_message = 6;
  int32 unread_count = 7;
  int64 created_at = 8;
}

message GetChatsRequest {}

message GetChatsResponse {
  repeated Chat chats = 1;
  string error = 2;
}

message CreateChatRequest {
  ChatType type = 1;
  string name = 2;
  repeated string participant_ids = 3;
}

message CreateChatResponse {
  Chat chat = 1;
  string error = 2;
}

// Messages

enum MessageType {
  TEXT = 0;
  FILE = 1;
  IMAGE = 2;
  SYSTEM = 3;
}

enum MessageStatus {
  SENT = 0;
  DELIVERED = 1;
  READ = 2;
}

message Message {
  string id = 1;
  string chatid = 2;
  string sender_id = 3;
  int64 timestamp = 4;
  MessageType type = 5;
  MessageStatus status = 6;
  string text = 7;
  string file_id = 8;
}

// Message requests

message GetMessagesRequest {
  string chatid = 1;
  int32 limit = 2;
  string cursor = 3;
}

message GetMessagesResponse {
  repeated Message messages = 1;
  string next_cursor = 2;
  string error = 3;
}

message SendMessageRequest {
  string chatid = 1;
  MessageType type = 2;
  string text = 3;
}

message SendMessageResponse {
  bool success = 1;
  Message message = 2;
  string error = 3;
}

// Stream

message StreamMessagesRequest {
  repeated string chatids = 1;
}

// Email

message RequestEmailCodeRequest {
  string email = 1;
}

message RequestEmailCodeResponse {
  bool success = 1;
  string error = 2;
}

message VerifyEmailCodeRequest {
  string email = 1;
  string code = 2;
}

// ADMIN

// Users

message CreateUserRequest  {
	string email = 1;
	string name = 2;
}

message UserResponse  {
	bool success = 1;
	User user = 2;
	string error = 3;
}

message GetUserByEmailRequest  {
	string email = 1;
}

message GetUserByEmailResponse  {
	bool success = 1;
	User user = 2;
	string error = 3;
}

message GetAllUsersRequest {}

message GetAllUsersResponse {
  repeated User users = 1;
  string error = 2;
}

message EditUserRequest  {
	string user_id = 1;
	optional string email = 2;
	optional string name = 3;
}

message DeleteUserRequest  {
	string user_id = 1;
}
